name: Run CI

on: [push, pull_request]

jobs:
  node-react-boilerplate:
    name: pipeline (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'secret'
          MYSQL_DATABASE: 'nrb-db'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'secret'
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        node-version: ['17.x']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2
    - name: Setup Env Variables
      run: |
          cp .env.example .env
          sed -i "s/APP_URL=http:\/\/localhost/APP_URL=http:\/\/127.0.0.1:8000/g" .env
          sed -i "s/3306/${{ job.services.mysql.ports['3306'] }}/g" .env
          sed -i "s/DB_HOST=mysql/DB_HOST=127.0.0.1/g" .env
          sed -i "s/local/testing/g" .env
    - name: Setup test environment
      run: |
          mkdir vendor
          cd vendor
          curl \
            https://chromedriver.storage.googleapis.com/96.0.4664.45/chromedriver_linux64.zip \
            --output chromedriver
    - name: Start Chrome Driver
      run: vendor/chromedriver &
    - name: Install dependencies
      run: pnpm install
    - run: sudo apt-get install xvfb
    - name: Run browser tests
      run: xvfb-run --auto-servernum pnpm test --env chrome

